Repository appuio/component-appuio-reporting, pull requests merged in 2024-02, with the labels that each got.

#20 Update `appuio/appuio-reporting` docker image to `v0.2.2`
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: dependency

#22 Add missing storage class `rbd-storagepool-cluster`
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: bug

#23 Remove default rules and move to config package
  class/defaults.yml
  tests/external-secret.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/suspended-cronjobs.yml
  tests/test-mode.yml
  tests/with-org-id.yml
Labels: enhancement
