Repository appuio/component-appuio-reporting, pull requests merged in 2024-01, with the labels that each got.

#10 Allow overriding `X-Scope-OrgID` on a per-rule basis
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/with-org-id.yml
Labels: enhancement

#9 Extend products list
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: change

#12 Update ghcr.io/appuio/appuio-reporting Docker tag to v0.2.1
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: dependency

#13 Fix product list
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: bug

#15 Make instance IDs unique
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: bug

#16 Syn APPUiO Cloud description patterns with AppCat
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: bug

#17 Deduplicate instance ID for OCP worker and storage nodes
  class/defaults.yml
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: bug

#18 Allow setting namespace metadata
  class/defaults.yml
  component/main.jsonnet
Labels: enhancement

#19 Spread out backfill jobs to keep resource usage more stable
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/external-secret/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/test-mode/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-reporting/appuio-reporting/11_backfill.yaml
  tests/golden/with-rules/appuio-reporting/appuio-reporting/11_backfill.yaml
Labels: breaking
